services:
  db:
    image: postgres:latest
    container_name: conceptual_library_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/library_data:/var/lib/postgresql/data
    ports:
      - "8432:5432"

  backend:
    container_name: conceptual_library_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    expose:
      - "80"
    ports:
      - "8000:80"
    depends_on:
      - db

  frontend:
    container_name: conceptual_library_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    ports:
      - "8888:80"
    depends_on:
      - db
      - backend

  nginx:
    container_name: conceptual_library_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
